### ISSUE TITLE
Contact Us link broken

### ISSUE THREAD

**Issue by Jameskmonger** [Davidw1339/townofsalemcompanion#1]
The "Contact Us" tab link is broken as there is no `contact.php` page.

Maybe it could be replaced with a link to the GitHub repo?

**Comment by waxmaster98** [comment]
It is a privacy issue, I will re add it later today, also you cannot run php locally. I will post the link to the actual website later today as well.

**Comment by Jameskmonger** [comment]
PHP can be executed locally on a local webserver, such as [XAMPP](https://www.apachefriends.org/index.html), [WAMP ](http://www.wampserver.com/en/) or even the [local webserver bundled with PHP 5.4.0](http://php.net/manual/en/features.commandline.webserver.php)

**Comment by Davidw1339** [comment]
Thank you for telling us James, the contact page has been re-added.
